"""initial migrate

Revision ID: 70a0ed36a537
Revises: 
Create Date: 2025-10-10 21:18:48.862504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a0ed36a537'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('rol_user', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_User_id_user'), 'User', ['id_user'], unique=False)
    op.create_table('Diagnosis',
    sa.Column('id_diagnosis', sa.UUID(), nullable=False),
    sa.Column('diagnosis_date', sa.Date(), nullable=False),
    sa.Column('diagnosis_description', sa.String(length=255), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_user_create', sa.UUID(), nullable=False),
    sa.Column('id_user_update', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_user_create'], ['User.id_user'], ),
    sa.ForeignKeyConstraint(['id_user_update'], ['User.id_user'], ),
    sa.PrimaryKeyConstraint('id_diagnosis')
    )
    op.create_index(op.f('ix_Diagnosis_id_diagnosis'), 'Diagnosis', ['id_diagnosis'], unique=False)
    op.create_table('User_Information',
    sa.Column('id_user_information', sa.UUID(), nullable=False),
    sa.Column('first_name_user', sa.String(length=50), nullable=False),
    sa.Column('second_name_user', sa.String(length=50), nullable=True),
    sa.Column('first_lastname_user', sa.String(length=50), nullable=False),
    sa.Column('second_lastname_user', sa.String(length=50), nullable=True),
    sa.Column('birth_date_user', sa.Date(), nullable=False),
    sa.Column('gender_user', sa.String(length=20), nullable=False),
    sa.Column('phone_number_user', sa.String(length=20), nullable=False),
    sa.Column('document_number_user', sa.String(length=30), nullable=False),
    sa.Column('id_user', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['User.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_user_information'),
    sa.UniqueConstraint('id_user')
    )
    op.create_index(op.f('ix_User_Information_id_user_information'), 'User_Information', ['id_user_information'], unique=False)
    op.create_table('Medic',
    sa.Column('id_medic', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=100), nullable=False),
    sa.Column('id_user_information', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_user_information'], ['User_Information.id_user_information'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_medic')
    )
    op.create_index(op.f('ix_Medic_id_medic'), 'Medic', ['id_medic'], unique=False)
    op.create_table('Nurse',
    sa.Column('id_nurse', sa.UUID(), nullable=False),
    sa.Column('speciality', sa.String(length=100), nullable=False),
    sa.Column('id_user_information', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_user_information'], ['User_Information.id_user_information'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_nurse'),
    sa.UniqueConstraint('id_user_information')
    )
    op.create_index(op.f('ix_Nurse_id_nurse'), 'Nurse', ['id_nurse'], unique=False)
    op.create_table('Patient',
    sa.Column('id_patient', sa.UUID(), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=False),
    sa.Column('id_user_information', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_user_information'], ['User_Information.id_user_information'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_patient'),
    sa.UniqueConstraint('id_user_information')
    )
    op.create_index(op.f('ix_Patient_blood_type'), 'Patient', ['blood_type'], unique=False)
    op.create_index(op.f('ix_Patient_id_patient'), 'Patient', ['id_patient'], unique=False)
    op.create_table('Medical_Appointment',
    sa.Column('id_medical_appointment', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_hour', sa.Time(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('id_medic', sa.UUID(), nullable=False),
    sa.Column('id_nurse', sa.UUID(), nullable=False),
    sa.Column('id_patient', sa.UUID(), nullable=False),
    sa.Column('id_diagnosis', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_diagnosis'], ['Diagnosis.id_diagnosis'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_medic'], ['Medic.id_medic'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_nurse'], ['Nurse.id_nurse'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_patient'], ['Patient.id_patient'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_medical_appointment')
    )
    op.create_index(op.f('ix_Medical_Appointment_id_medical_appointment'), 'Medical_Appointment', ['id_medical_appointment'], unique=False)
    op.create_table('Bill',
    sa.Column('id_bill', sa.UUID(), nullable=False),
    sa.Column('generation_date', sa.Date(), nullable=False),
    sa.Column('generation_hour', sa.Time(), nullable=False),
    sa.Column('total', sa.Float(precision=10), nullable=False),
    sa.Column('id_patient', sa.UUID(), nullable=False),
    sa.Column('id_medical_appointment', sa.UUID(), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id_user_create', sa.UUID(), nullable=False),
    sa.Column('id_user_update', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id_medical_appointment'], ['Medical_Appointment.id_medical_appointment'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_patient'], ['Patient.id_patient'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user_create'], ['User.id_user'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user_update'], ['User.id_user'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_bill'),
    sa.UniqueConstraint('id_medical_appointment')
    )
    op.create_index(op.f('ix_Bill_id_bill'), 'Bill', ['id_bill'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bill_id_bill'), table_name='Bill')
    op.drop_table('Bill')
    op.drop_index(op.f('ix_Medical_Appointment_id_medical_appointment'), table_name='Medical_Appointment')
    op.drop_table('Medical_Appointment')
    op.drop_index(op.f('ix_Patient_id_patient'), table_name='Patient')
    op.drop_index(op.f('ix_Patient_blood_type'), table_name='Patient')
    op.drop_table('Patient')
    op.drop_index(op.f('ix_Nurse_id_nurse'), table_name='Nurse')
    op.drop_table('Nurse')
    op.drop_index(op.f('ix_Medic_id_medic'), table_name='Medic')
    op.drop_table('Medic')
    op.drop_index(op.f('ix_User_Information_id_user_information'), table_name='User_Information')
    op.drop_table('User_Information')
    op.drop_index(op.f('ix_Diagnosis_id_diagnosis'), table_name='Diagnosis')
    op.drop_table('Diagnosis')
    op.drop_index(op.f('ix_User_id_user'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
